export const urduLanguageData = {
    Cleanliness: 'مسلم سوسائٹی میں صفائی',
    'Eating Habbits': 'کھانے کی عادتیں',
    'Food Waste': 'خوراک ضائع کرنا',
    'Pornography and Adult films': 'فحش ننگی فلمیں ',
    'Cloths Charity': 'استعمال شدہ لباس  کا  صدقہ',
    'Dispute Solving': ' جھگڑے کو حل کرنا ',
    'Khatme Nabuwat': 'ختم نبوت',
    'haj and Umrah': 'حج اور  امرا',
    home_menu: 'پہلا صفہ',
    naat: 'نعت ',
    Topics: 'موجودہ مسائل',
    'Social Issues': 'معاشرتی مسائل',
    'Economical Issues': 'معاشی مسائل',
    'Religious Issues': 'مذہبی مسائل',
    Guidelines: 'ہدایات',
    'Marriage Guidelines': 'شادی کی ہدایات',
    'Parenting Guidelines': 'والدین کے لئے ہدایت ',
    'Special Messages': 'خصوصی پیغام',
    'Special Occasions': 'خاص موقع',
    latest_ternding_menu: 'تازہ ترین رجحان',
    contact_menu: 'رابطہ کریں',
    book_download_menu: 'کتاب ',
    language_menu: 'A अ ب ',
    darul_qaza_menu: ' جھگڑے کو حل کرنا ',
    'Islamic History': ' اسلامی تاریخ',
    'About Us': 'ہمارے بارے میں',
    Others: 'دوسرے عنوانات',
    nav_menu: 'فہرست ',
    'Understanding Quran': 'قرآن نہیں سمجھنا ',
    'Seerat un Nabi': 'سیرت ان نبی نہیں جاننا',
    'Property Distribution': 'جائیداد کی تقسیم ہندوستان کے مسلمانوں میں',
    Cleanliness_in_Muslim_Society: 'مسلم سوسائٹی میں صفائی',
    Good_Bad_Eating_Habits: 'اچھ  اور خراب کھانا  کھانے کی عادتیں',
    'Court Involvment': 'شادی کے بعد عدالتی مقدمہ ',
    'Money Lending': 'رقم قرض دینے کے لئے ہدایات',
    'Buisiness Improvment': 'کاروبار میں ترقی کیسے کریں ',
    Building_Maintenance: 'بلڈنگ بحالی',
    'Talaq and Khula': 'طلاق خلہ ',
    Food_Wasting: 'خوراک ضائع کرنا',
    'Social Media': 'سوشل میڈیا کا استعمال',
    Pornography: 'فحش ننگی فلمیں ',
    'Used Cloths': 'استعمال شدہ لباس  کا  صدقہ',
    'Living with Non-Muslims': 'غیر مسلم کے ساتھ رہنا ',
    marriage_non_Muslim: 'غمقدماتیر مسلم کے ساتھ شادی',
    Janazah: 'جنازہ',
    'Shabe-E-Meraj or Barat or Qadr': 'شب مرگ / بارات / قادر',
    'Street Beggers': 'راستے اور مسجد  کے فقیر ',
    'Daswa Chilla Barsi': 'دسوا چللہ برسی ',
    Corruption: 'بدعنوانی',
    'Missing Fajr': 'فجر ک لئے اٹھنا ',
    'Destiny and Planning': 'تقدیر یا منصوبہ بندی',
    'Azan and its Volume': 'غلط اذان اور اسپیکر کا حجم',
    'Family System in West': 'مغرب میں خاندانی نظام',
    'Marriage Age': 'شادی کب کرنی چاہیے ',
    'Wedding Preparation': 'شادی کی تیاری',
    'Right Life Partner': 'شریک حیات کی تلاش ',
    Engagement: 'منگنی ',
    'Wedding Expenses': 'شادی کے اخراجات',
    Dowry: 'جہیز',
    'Post Wedding Life': 'شادی کے بعد',
    'Saas and Sasur': 'ساس اور سسر  ',
    'Husband and Wife Love': 'شوہر بیوی سے محبت',
    'Husband and wife fighting': 'شوہر بیوی کی لڑائی ',

    'Upto 5 years': 'پانچ سال تک کے بچے',
    '5 to 10 years': 'پانچ سے دس  سال کے بچے',
    '10 to 20 years': 'دس سے بیس سال کے  بچے ',
    Up_25_to_5_Years: 'پچیس سے پینتیس سال کے بچے',

    'To Ulama': 'علما ',
    'To Doctors': 'ڈاکٹر',
    select_p: 'اپنا پیشہ منتخب کریں',
    business: 'تاجر',
    'To Engineers': 'انجینئر',
    'To Lawyers': 'وکیل',
    'To Teachers': 'اساتذہ',
    'To Buisnessmen': 'تاجر',
    'To Butchers': 'قریشی',
    'To Masjid Trustee': 'مسجد ٹرسٹی ',

    'Eid ul-Fitr': 'عیدالفطر ',
    'Eid Ul-Adha': 'عیدلاظہا ',
    'Milad un Nabi': 'عید میلادننبی  ',
    Moharram: 'محرم',
    'Salatul Istisqa': 'سلامتی',

    'Muslim in Freedom of India': 'ہندوستان کی آزادی میں مسلم',
    'Muslim Scientist': 'مسلم سائنسدان',
    'How Old is Islam': 'اسلام کتنا پرانا ہے',
    Education: 'تعلیم میں ہندوستان کے مسلمان ',
    'Misconseption About Islam': 'اسلام کے بارے میں غلط فہمی',
    firstname: 'نام',
    gender: 'صنف',
    age: 'عمر',
    city: 'شہر',
    taluka: 'تعلقہ /شہر',
    village: 'گاؤں / علاقہ',
    masjid: 'نزدیکی مسجد ',
    phonenumber: 'فون نمبر ',
    male: 'مرد',
    female: 'عورت',
    selectage: 'عمر کا انتخاب کریں۔',
    selecttaluka: 'منتخب کریں',

    nearestmasjid: 'نزدیکی مسجد ',

    profession: 'پیشہ',
    trusty: 'مسجد زیمدار',
    i_trusty: 'ٹرسٹی ',
    doctor: 'ڈاکٹر',
    engineer: 'انجینئر',
    lawyer: 'وکیل',
    mr: 'M.R',
    pharmacist: 'فارماسسٹ',
    student: 'طالب علم',
    teacher: 'استاد',
    housewife: 'گھریلو خاتون',

    select_i: 'براہ مہربانی منتخب کریں',
    interest: 'دلچسپی کا علاقہ',
    charity: 'صدقہ',
    school: 'اسکول کی تعلیم',
    madrasa: 'مدرسہ اور مکتب',
    health: 'صحت اور دوائی',
    journalism: 'صحافت',
    hygiene: 'صحت اور حفظان صحت',
    schemes: 'اسکالرشپ اور سکیمیں',
    assistance: 'ملازمت میں مدد',
    teaching: 'پڑھانا',

    not: 'میں نہیں ہوں',
    muezzin: 'مین موزان ہو',
    Imam: 'میں امام ہوں',
    'Become a member': 'ممبر بنیں',
    taluka_u: 'اپنا تالکا منتخب کریں',

    'Apply for Govt. Documents':
        'پاسپورٹ / آدھار کارڈ / پین کارڈ کے لئے کس طرح درخواست دیں',
    'Train and Flight tickets Booking':
        'آن لائن ٹرین / فلائٹ ٹکٹ کیسے بک کروائیں',
    Scholarship: 'وظیفہ',
    'What is KYC': 'کیا ہے  KYC',
    prepare_aadhar_voter_id: 'آدھار کارڈ / ووٹر شناختی کارڈ کیسے تیار کریں',
    'Using UPI / Paytm': 'گوگل پے / پے ٹی ایم کا استعمال کیسے کریں',
    Books: 'کتابیں',
};
